services:
  app:
    container_name: app
    image: node
    build:
      context: ./
      dockerfile: ./src/Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./src:/usr/src/app/src
      - /usr/src/app/node_modules
    env_file:
      - .env.dev
    command: ['npm', 'run', 'dev']
