services:
  app:
    container_name: app
    build:
      context: ./
      dockerfile: ./src/Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./src:/usr/app/src
      - /usr/app/node_modules
    env_file:
      - .env.dev
    command: ['npm', 'run', 'dev']
