services:
  app:
    container_name: app
    # restart: on-failure
    build:
      context: ./
      dockerfile: ./src/ Dockerfile
    volumes:
      - /usr/src/app/node_modules
    ports:
      - '8000'
  nginx:
    container_name: nginx
    restart: on-failure
    build:
      context: ./nginx
      dockerfile: ./nginx/Dockerfile
    ports:
      - '80'
    depends_on:
      - app
  # mysql:
  #   restart: on-failure
  #   build: ./mysql
  #   ports:
  #     - '3306'
